# Generated by Django 5.2.15 on 2026-06-25 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_url', models.TextField(blank=True, null=True, verbose_name='录音地址')),
                ('transcript', models.TextField(blank=True, null=True, verbose_name='转录文本')),
                ('scores', models.JSONField(blank=True, help_text='{"confidence":85,"structure":72,...}', null=True, verbose_name='评分')),
                ('feedback', models.JSONField(blank=True, help_text='{"strengths":[],"improvements":[],...}', null=True, verbose_name='反馈')),
                ('duration_sec', models.IntegerField(default=0, verbose_name='时长(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson', verbose_name='课程')),
            ],
            options={
                'verbose_name': '练习记录',
                'verbose_name_plural': '练习记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
