# Generated by Django 5.2.15 on 2026-06-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=32, unique=True, verbose_name='订单号')),
                ('plan_type', models.CharField(choices=[('monthly', '月度'), ('quarterly', '季度'), ('yearly', '年度')], max_length=20, verbose_name='套餐类型')),
                ('amount_cents', models.IntegerField(verbose_name='金额(分)')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('expired', '已过期'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='状态')),
                ('channel', models.CharField(blank=True, help_text='alipay|wxpay', max_length=20, null=True, verbose_name='支付渠道')),
                ('trade_no', models.CharField(blank=True, help_text='支付平台交易号', max_length=64, null=True, verbose_name='交易号')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '支付订单',
                'verbose_name_plural': '支付订单',
                'ordering': ['-created_at'],
            },
        ),
    ]
