# Generated by Django 5.2.15 on 2026-06-25 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_id', models.IntegerField(help_text='1-5阶', verbose_name='阶段')),
                ('lesson_id', models.IntegerField(verbose_name='课程序号')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('prompt_key', models.CharField(max_length=50, verbose_name='Prompt模板')),
                ('exercise_type', models.CharField(choices=[('speech', '有准备演讲'), ('impromptu', '即兴表达'), ('story', '故事讲述'), ('debate', '辩论/说服')], max_length=30, verbose_name='练习类型')),
                ('duration_goal', models.IntegerField(default=60, verbose_name='目标时长(秒)')),
                ('is_free', models.BooleanField(default=True, verbose_name='免费')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'ordering': ['level_id', 'sort_order'],
                'unique_together': {('level_id', 'lesson_id')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', '未解锁'), ('unlocked', '已解锁'), ('completed', '已完成')], default='locked', max_length=20, verbose_name='状态')),
                ('best_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='最高分')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson', verbose_name='课程')),
            ],
            options={
                'verbose_name': '用户进度',
                'verbose_name_plural': '用户进度',
            },
        ),
    ]
