# Generated by Django 5.2.15 on 2026-06-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='example_text',
            field=models.TextField(blank=True, default='', verbose_name='范例文本'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='theory_content',
            field=models.TextField(blank=True, default='', verbose_name='理论讲解'),
        ),
    ]
