# Generated by Django 5.2.15 on 2026-08-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_password', models.CharField(max_length=128, verbose_name='邮箱授权密码')),
                ('smtp_host', models.CharField(max_length=128, verbose_name='SMTP服务器地址')),
                ('smtp_port', models.IntegerField(default=465, verbose_name='邮箱端口号')),
                ('smtp_user', models.EmailField(max_length=254, verbose_name='邮箱地址')),
                ('sender_name', models.CharField(blank=True, max_length=64, verbose_name='自定义发件人昵称')),
            ],
            options={
                'verbose_name': '邮箱配置',
                'verbose_name_plural': '邮箱配置',
                'db_table': 'e_mail',
            },
        ),
        migrations.CreateModel(
            name='EmailVerifyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('code', models.CharField(max_length=6, verbose_name='验证码')),
                ('purpose', models.CharField(default='verify', help_text='verify|login|change_password|reset_password', max_length=20, verbose_name='用途')),
                ('used', models.BooleanField(default=False, verbose_name='已使用')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'used', 'expires_at'], name='e_mail_emai_email_0a41fe_idx')],
            },
        ),
    ]
